Valentin Lorenzo Carroza Granifo 22.437.518-2

In [14]:
import numpy as np

# Importa la biblioteca de numpy

In [15]:
rng = np.random.default_rng(seed=800)

# Elige numeros "aleatorios" entre 0 y 800

In [18]:
L = [1.0, 2.5, 0.8, 5.0, 10.0]
d = [10, 25, 15, 40, 60]

In [25]:
arreglo_L = np.array(L)
arreglo_d = np.array(d)

# Convierte las listas de python en arreglos

In [43]:
def calc_flujo(L, d):
    """
    Calcula el flujo de las estrellas.

    Parameters
    ----------
    L = numpy.ndarray
        Datos de luminosidad de cada estrella.
    d = numpy.ndarray
        Datos de distancia de caada estrella

    Returns
    -------
    numpy.ndarray
        Resultado de la formula de flujo para cada dato.
    """
    flujo = L / (4 * np.pi * np.power(d, 2))
    return flujo
    
flujo = calc_flujo(arreglo_L, arreglo_d)

In [81]:
print(np.where(flujo == np.max(flujo))) # Imprime el indice del flujo mayor.

(array([0]),)


In [80]:
print(np.where(flujo == np.min(flujo))) # Imprime el indice del flujo menor.

(array([4]),)


In [53]:
print(np.mean(flujo)) # Imprime el promedio de los flujos.

0.00037335097066973783


In [54]:
print(np.median(flujo)) # Imprime la mediana de flujos.

0.0002829421210522584


In [62]:
mask = flujo >= 10**-11 # Mascara booleana que muestra solo los flujos mayores a 10^-11

In [64]:
flujo[mask] # Imprime el arreglo aplicando la mascara

array([0.00079577, 0.00031831, 0.00028294, 0.00024868, 0.00022105])

In [84]:
np.flip(flujo[np.argsort(flujo, axis=0)]) # Imprime los datos de flujo ordenados de mayor a menor

array([0.00079577, 0.00031831, 0.00028294, 0.00024868, 0.00022105])